version: 2
jobs:
  linux:
    docker:
      - image: rocker/verse:latest
    steps:
      - checkout
      - run:
          name: Install
          command: |
              R -e 'devtools::install(".", dependencies = TRUE, upgrade_dependencies = FALSE)'
      - run:
          name: Render paper
          command: |
              R -e "rmarkdown::render('./paper/swtp.Rmd', output_file = "../docs/index.html")"

workflows:
  version: 2
  build_and_test:
    jobs:
      - linux
